runtime: python39
service: frontend

handlers:
# Version endpoint - NEVER cache (MUST BE FIRST)
- url: /version.json
  static_files: version.json
  upload: version.json
  secure: always
  http_headers:
    Cache-Control: "no-cache, no-store, must-revalidate, max-age=0"
    Pragma: "no-cache"
    Expires: "0"
    Vary: "*"

# Service worker - no cache
- url: /sw.js
  static_files: sw.js
  upload: sw.js
  secure: always
  http_headers:
    Cache-Control: "no-cache, no-store, must-revalidate"
    Service-Worker-Allowed: "/"

# Config file - no cache for version updates
- url: /config.js
  static_files: config.js
  upload: config.js
  secure: always
  http_headers:
    Cache-Control: "no-cache, no-store, must-revalidate"
    Pragma: "no-cache"
    Expires: "0"

# Index.html - no cache
- url: /index.html
  static_files: index.html
  upload: index.html
  secure: always
  http_headers:
    Cache-Control: "no-cache, no-store, must-revalidate"
    Pragma: "no-cache"
    Expires: "0"

# Static assets with caching (excluding critical files)
- url: /(.*\.(css|png|jpg|jpeg|gif|ico|svg|webp))$
  static_files: \1
  upload: .*\.(css|png|jpg|jpeg|gif|ico|svg|webp)$
  secure: always
  http_headers:
    Cache-Control: "public, max-age=31536000"

# Other JS files - shorter cache
- url: /(.*\.js)$
  static_files: \1
  upload: .*\.js$
  secure: always
  http_headers:
    Cache-Control: "public, max-age=3600"

# Manifest
- url: /manifest.json
  static_files: manifest.json
  upload: manifest.json
  secure: always
  http_headers:
    Content-Type: "application/manifest+json"

# Test page
- url: /test-hosting.html
  static_files: test-hosting.html
  upload: test-hosting.html
  secure: always

# Force update page
- url: /force-update.html
  static_files: force-update.html
  upload: force-update.html
  secure: always
  http_headers:
    Cache-Control: "no-cache, no-store, must-revalidate"

# Main app - always serve index.html for SPA routing
- url: /.*
  static_files: index.html
  upload: index.html
  secure: always
  http_headers:
    Cache-Control: "no-cache, no-store, must-revalidate"
    Pragma: "no-cache"
    Expires: "0"

