runtime: nodejs20
service: sales-tracker-api

# Environment variables (non-sensitive only)
env_variables:
  NODE_ENV: production
  USE_SECRET_MANAGER: "true"
  GOOGLE_CLOUD_PROJECT: salesappfkt

# Automatic scaling configuration
automatic_scaling:
  min_instances: 0
  max_instances: 2
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 10

# Resource allocation for small scale
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

# Network settings
network:
  session_affinity: true

# Health checks
readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2

# Handlers
handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: "301"