runtime: nodejs20
service: sales-tracker-api

# Environment variables
env_variables:
  LINE_CHANNEL_ACCESS_TOKEN: "p16MHJa6Wbc8IqZ0EzBGcMC/oAs9zo9MAQ0fSqZ8GCi7tgvQIDeuqNXhI93FetCMeBluaMRgyCsI0z6aA7dh9IvCFKUYoLBgTwaERUkjCYphrdJNQINsDbeFIOHCcamYjZJe7K0UXldyN61WD/uRPwdB04t89/1O/w1cDnyilFU="
  LINE_CHANNEL_SECRET: "729d399073b6755757f9b215ee43f037"
  LINE_GROUP_ID: "C3625de59977b799d812357ac738c5c9b"
  NODE_ENV: production

# Automatic scaling configuration
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

# Resource allocation
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

# Network settings
network:
  session_affinity: false

# Health checks
readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2

# Handlers for static files and API routes
handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301