#!/bin/bash

echo "🚀 Manual Deploy to Render"
echo "=========================="
echo ""
echo "Since auto-deploy is not set up, you can:"
echo ""
echo "1. Go to https://dashboard.render.com"
echo "2. Find your 'sales-tracker-backend' service"
echo "3. Click 'Manual Deploy' → 'Deploy latest commit'"
echo ""
echo "OR"
echo ""
echo "Set up auto-deploy by:"
echo "1. In Render dashboard, go to your service"
echo "2. Settings → Build & Deploy"
echo "3. Auto-Deploy: ON"
echo "4. Branch: main"
echo ""
echo "Your backend URL will be:"
echo "https://sales-tracker-backend.onrender.com"