name: Deploy Backend to Render

on:
  push:
    branches: [ main ]
    paths: [ 'backend/**' ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to Render
      uses: bounceapp/render-action@0.6.0
      with:
        render-token: ${{ secrets.RENDER_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        service-id: ${{ secrets.RENDER_SERVICE_ID }}
        retries: 5
        wait: true
        sleep: 30000